name: Taging Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Abhängigkeiten installieren
      run: npm i

    - name: tag-version
      uses: juliansangillo/tag-version@v1.5

    - uses: "actions/checkout@master"
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@v4.6.8"
      id: "todo"