name: Taging Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       # node-version: [12.x, 14.x, 16.x]
       node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Abhängigkeiten installieren
      run: npm i

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      
    - name: Git Version
      uses: codacy/git-version@2.4.0


    - name: todo-issue
      uses: DerJuulsn/todo-issue@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
